apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ghost-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0fce0d41ec11e396e
  directoryPerms: "700"