apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer   # ✅ quan trọng cho EBS
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: "false"
allowedTopologies:
  - matchLabelExpressions:
      - key: eks.amazonaws.com/compute-type
        values:
          - auto