apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 86.1.0
      helm:
        skipCrds: true          # ← skip CRDs, đã handle riêng
        valueFiles:
          - $values/prometheus/values.yaml
    - repoURL: https://github.com/phuleshi/sre-project.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: Prometheus
      jsonPointers:
        - /spec/livenessProbe
        - /spec/readinessProbe