apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.auth.password | quote }}
