apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "65.1.1"
    helm:
      valueFiles:
        - $values/prometheus/values.yaml   # trỏ đúng path trong repo

    repoURL: https://github.com/phuleshi/sre-project  # ← SỬA
    targetRevision: main                                      # ← SỬA nếu dùng branch khác
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
