# Prometheus Community kube-prometheus-stack

prometheus:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-type: external
  prometheusSpec:
    retention: 10d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
    additionalScrapeConfigs:
      - job_name: ghost-mysql-metrics
        scrape_interval: 30s
        static_configs:
          - targets:
              - ghost-mysql-metrics.app.svc.cluster.local:9104

alertmanager:
  enabled: false        # tắt để tiết kiệm RAM

grafana:
  enabled: false        # tắt để tiết kiệm RAM

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi