# Ghost Configuration
ghost:
  image:
    repository: ghost
    tag: "5.87.2-alpine"
    pullPolicy: IfNotPresent

  # Blog settings
  url: "k8s-app-ghostgho-b51cc9977d-974120bade00318e.elb.ap-northeast-1.amazonaws.com"  # e.g. http://your-elb-dns.amazonaws.com
  blogTitle: "User's Blog"

  # Admin account
  adminEmail: "user@example.com"

  replicaCount: 1

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    enabled: true
    storageClass: "ghost-efs-sc"
    accessMode: ReadWriteMany
    size: 8Gi

  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-type: external

# MySQL Configuration
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  auth:
    rootPassword: "rootpassword"
    database: "ghost"
    username: "ghost"
    password: "ghostpassword"

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    enabled: true
    storageClass: "gp2"
    accessMode: ReadWriteOnce
    size: 8Gi
